version: '3.6'

services:
    magento:
        image: cagartner/magento-apache-7.1
        ports:
        - "80:80"
        expose:
        - "9000"
        volumes:
        - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
        - ./docker/fpm.conf:/etc/php/7.1/fpm/pool.d/www.conf
        - ./docker/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini
        - ./docker/logs/:/var/log/apache2
        - ./:/var/www/html
        environment:
        - TERM=xterm-256color
        - APACHE_RUN_USER=1000
        networks:
            default:
                aliases:
                - ${SERVER_NAME}
                - ${SERVER_ALIAS}

    db:
        image: mysql:5.7
        volumes:
        - ./docker/db:/var/lib/mysql

        ports:
        - "3306:3306"

        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        image: redis
        ports:
        - 6379

    redis-session:
        image: redis
        ports:
        - 6379

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - '8080:80'
        environment:
            MYSQL_USERNAME: ${MYSQL_ROOT_USERNAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}